### ISSUE TITLE
how does this parsing tool include the keyword “NOT”

### ISSUE THREAD

**Issue by crack521** [nikitaKunevich/logical-expression-parser#1]
Hello, how does this parsing tool include the “NOT” keyword? For example,  can it parse the following sentences?
    '(NOT (Gender = "m")) AND (age > 25 OR (seniority > 5 AND position!= "Manager"))'
Thanks!

**Comment by nikitakunevich** [comment]
Hi!
It does not.
Check out file with grammar, to see what this parser can parse:
https://github.com/nikitaKunevich/logical-expression-parser/blob/master/parser.py
